apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: pubsub
spec:
  type: pubsub.redis
  version: v1
  metadata:
    - name: redisHost
      secretKeyRef:
        name: REDIS_HOST
        key: REDIS_HOST

auth:
  secretStore: envvar-secret-store
